const EBOOKS = [
  {
    id: "accessoires-technologiques",
    title: "Annuaire Accessoires Technologiques",
    description: "Répertoire d'images — accessoires technologiques.",
    cover: "assets/ebooks/covers/accessoires_technologiques.png",
    file: "assets/ebooks/extracted/Annuaire_Accessoires_Technologiques_Images.zip",
    price: 17.9,
    suppliers: 1037,
  },
  {
    id: "alimentaires",
    title: "Annuaire Alimentaires",
    description: "Répertoire d'images — produits alimentaires.",
    cover: "assets/ebooks/covers/alimentaires.png",
    file: "assets/ebooks/extracted/Annuaire_Alimentaires_Images.zip",
    price: 19.9,
    suppliers: 3048,
  },
  {
    id: "automobiles",
    title: "Annuaire Automobiles",
    description: "Répertoire d'images — automobiles.",
    cover: "assets/ebooks/covers/automobiles.png",
    file: "assets/ebooks/extracted/Annuaire_Automobiles_Images.zip",
    price: 19.9,
    suppliers: 5817,
  },
  {
    id: "cosmetiques",
    title: "Annuaire Cosmétiques",
    description: "Répertoire d'images — cosmétiques.",
    cover: "assets/ebooks/covers/cosmetiques.png",
    file: "assets/ebooks/extracted/Annuaire_Cosmetiques_Images.zip",
    price: 18.9,
    suppliers: 2250,
  },
  {
    id: "decorations",
    title: "Annuaire Décorations",
    description: "Répertoire d'images — décorations.",
    cover: "assets/ebooks/covers/decorations.png",
    file: "assets/ebooks/extracted/Annuaire_Decorations_Images.zip",
    price: 17.9,
    suppliers: 1913,
  },
  {
    id: "electromenagers",
    title: "Annuaire Électroménagers",
    description: "Répertoire d'images — électroménagers.",
    cover: "assets/ebooks/covers/electromenagers.png",
    file: "assets/ebooks/extracted/Annuaire_Electromenagers_Images.zip",
    price: 15.9,
    suppliers: 814,
  },
  {
    id: "livres",
    title: "Annuaire Livres",
    description: "Répertoire d'images — livres.",
    cover: "assets/ebooks/covers/livres.png",
    file: "assets/ebooks/extracted/Annuaire_Livres_Images.zip",
    price: 0,
    suppliers: 3974,
  },
  {
    id: "matiere-premiere",
    title: "Annuaire Matière Première",
    description: "Répertoire d'images — matières premières.",
    cover: "assets/ebooks/covers/matiere_premiere.png",
    file: "assets/ebooks/extracted/Annuaire_Matiere_Premiere_Images.zip",
    price: 19.9,
    suppliers: 14640,
  },
  {
    id: "miels",
    title: "Annuaire Miels",
    description: "Répertoire d'images — miels.",
    cover: "assets/ebooks/covers/miels.png",
    file: "assets/ebooks/extracted/Annuaire_Miels_Images.zip",
    price: 12.9,
    suppliers: 398,
  },
  {
    id: "montres",
    title: "Annuaire Montres",
    description: "Répertoire d'images — montres.",
    cover: "assets/ebooks/covers/montres.png",
    file: "assets/ebooks/extracted/Annuaire_Montres_Images.zip",
    price: 14.9,
    suppliers: 543,
  },
  {
    id: "packaging",
    title: "Annuaire Packaging",
    description: "Répertoire d'images — packaging.",
    cover: "assets/ebooks/covers/packaging.png",
    file: "assets/ebooks/extracted/Annuaire_Packaging_Images.zip",
    price: 15.9,
    suppliers: 797,
  },
  {
    id: "papeteries",
    title: "Annuaire Papeteries",
    description: "Répertoire d'images — papeteries.",
    cover: "assets/ebooks/covers/papeteries.png",
    file: "assets/ebooks/extracted/Annuaire_Papeteries_Images.zip",
    price: 19.9,
    suppliers: 5722,
  },
  {
    id: "parfums",
    title: "Annuaire Parfums",
    description: "Répertoire d'images — parfums.",
    cover: "assets/ebooks/covers/parfums.png",
    file: "assets/ebooks/extracted/Annuaire_Parfums_Images.zip",
    price: 17.9,
    suppliers: 1048,
  },
  {
    id: "personnalisation",
    title: "Annuaire Personnalisation",
    description: "Répertoire d'images — personnalisation.",
    cover: "assets/ebooks/covers/personnalisation.png",
    file: "assets/ebooks/extracted/Annuaire_Personnalisation_Images.zip",
    price: 17.9,
    suppliers: 1905,
  },
  {
    id: "plantes",
    title: "Annuaire Plantes",
    description: "Répertoire d'images — plantes.",
    cover: "assets/ebooks/covers/plantes.png",
    file: "assets/ebooks/extracted/Annuaire_Plantes_Images.zip",
    price: 19.9,
    suppliers: 4507,
  },
  {
    id: "sacs",
    title: "Annuaire Sacs",
    description: "Répertoire d'images — sacs.",
    cover: "assets/ebooks/covers/sacs.png",
    file: "assets/ebooks/extracted/Annuaire_Sacs_Images.zip",
    price: 9.9,
    suppliers: 202,
  },
  {
    id: "soins-capillaires",
    title: "Annuaire Soins Capillaires",
    description: "Répertoire d'images — soins capillaires.",
    cover: "assets/ebooks/covers/soins_capillaires.png",
    file: "assets/ebooks/extracted/Annuaire_Soins_Capillaires_Images.zip",
    price: 15.9,
    suppliers: 784,
  },
];

const EBOOKS_TOTAL_SUPPLIERS = 49399;
